config/routes.rb
DebetManager::Application.routes.draw do
  resources :debts
  root :to => 'debts#index'
end

app/models/debt.rb
class Debt < ActiveRecord::Base
  attr_accessible :amount, :name, :repaid

  validates :amount, :numericality => { :greater_than => 0 }
  validates :repaid, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => :amount }
  validates :name, :presence => true

  def percento
  	( self.repaid / self.amount ) * 100.0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  def index
  	@debts = Debt.all
  end

  def new
  	@debt = Debt.new
  end

  def create
  	@debt = Debt.new params[:debt]

  	if @debt.save
  		redirect_to debts_path
  	else
  		render :new
  	end
  end

  def edit
  	@debt = Debt.find params[:id]
  end

  def update
  	@debt = Debt.find params[:id]
  	# @debt.name = params[:debt][:name]
  	# @debt.amount = params[:debt][:amount]
    params[:debt][:repaid] = params[:debt][:repaid].to_i + params[:splatka].to_i

  	if @debt.update_attributes params[:debt]
	  	# if @debt.save
	  	# @debt.repaid = @debt.repaid + params[:splatka].to_i
	  	# @debt.save
			# @debt.update_attribute :repaid, @debt.repaid + params[:splatka].to_i
  		redirect_to debts_path
  	else
  		render :edit
  	end
  end

  def destroy
    @album = Debt.find params[:id]
    @album.destroy
    redirect_to debts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/views/debts/_debt.html.erb
<li>
	<fieldset>
	<legend class="shadow"> <%= debt.name  %> </legend>

		<span>dlžná čiastka: <%= number_to_currency debt.amount %></span>
		<span>splatené: <%= number_to_percentage debt.percento , :precision => 2 %></span>
		<div class="progress">
			<span class="percent"><%= number_to_percentage debt.percento , :precision => 2 %></span>
			<div style="width: <%= number_to_percentage debt.percento , :precision => 1 %>">&nbsp;</div>
		</div>
		<div class="repaid">
			<div style="margin-left: <%= number_to_percentage debt.percento , :precision => 1 %>">
				<%= number_to_currency debt.repaid %>
			</div>
		</div>

		<nav>
			<%= link_to "Uprav", edit_debt_path(debt), :class => 'shadow button'  %>
			<%= link_to "Vymaž", debt_path(debt),
					:method => :delete,
					:data =>{ :confirm => "Chceš to naozaj zmazať?"},
					:class => 'shadow button'  %>
		</nav>
	</fieldset>
</li>

app/views/debts/_form.html.erb
<fieldset>
<legend class="shadow"> Dlh </legend>
<%= form_for @debt do |f| %>
	<ul class="errors">
	<% @debt.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
	</ul>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'shadow' %>
  </p>
  <p>
    <%= f.label :amount %>
    <%= f.text_field :amount, :class => 'shadow' %>
  </p>
  <p>
    <%= f.label :repaid %>
    <%= f.text_field :repaid, :class => 'shadow' %>
  </p>
  <p>
    <%= label_tag :splatka %>
    <%= text_field_tag :splatka, nil, :class => 'shadow' %>
  </p>
  <nav>
    <%= f.submit "Uložiť", :class => 'shadow button' %>&nbsp;<%= link_to "Späť", debts_path, :class => 'shadow button' %>
  </nav>
<% end %>
</fieldset>

app/views/debts/edit.html.erb
<h2>Uprav dlh</h2>
<%= render "form" %>

app/views/debts/index.html.erb
<%= link_to "Nový dlh", new_debt_path, :class => 'shadow button' %>
<ul>
<% if @debts.any? %>
	<%= render @debts %>
<% else %>
  <li>Super !!!!!  nemáš ešte žiaden dlh.</li>
<% end %>
</ul>

app/views/debts/new.html.erb
<h2>Nový dlh</h2>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Debt Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <div class="header">
    <h1><%= link_to "Manažment dlhov", root_path %> &mdash; 16.deň learn2code úloha</h1>
  </div>
	<%= yield %>
  <div class="clear"></div>
</div>
<div class="footer">learn2code :werdyii </div>

</body>
</html>